version: 0.0
os: linux

files:
  - source: gin_demo
    destination: ~/

hooks:
  BeforeInstall:
    - location: ./codedeploy/beforeInstall.sh
      timeout: 180
      runas: ubuntu-v4
  AfterInstall:
    - location: ./codedeploy/afterInstall.sh
      timeout: 180
      runas: ubuntu-v4
  ApplicationStart:
    - location: ./codedeploy/applicationStart.sh
      timeout: 180
      runas: ubuntu-v4
